import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Link from 'next/link';
import './globals.css';
import Provider from './components/Provider';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex items-end gap-8 p-8">
          <Link href="/" className="block">
            <h1 className="text-6xl">React map app</h1>
          </Link>
          <Link href="/lists" className="block">
            <h2 className="text-xl">lists</h2>
          </Link>
          <Link href="/form" className="block">
            <h2 className="text-xl">form</h2>
          </Link>
        </header>
        <div className="px-8">
          <Provider>{children}</Provider>
        </div>
      </body>
    </html>
  );
}
